version: '3.9'
name: grafana-postgres
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pg}
    ports:
      - "${POSTGRES_PORT:-15432}:5432"
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data
  grafana:
    image: grafana/grafana:latest
    environment:
      GF_DATABASE_TYPE: postgres
      GF_DATABASE_HOST: ${GF_DATABASE_HOST:-postgres}
      GF_DATABASE_NAME: ${GF_DATABASE_NAME:-postgres}
      GF_DATABASE_USER: ${GF_DATABASE_USER:-postgres}
      GF_DATABASE_PASSWORD: ${GF_DATABASE_NAME:-pg}
      GF_DATABASE_SSL_MODE: disable
    restart: always
    depends_on:
        - postgres
    ports:
      - ${GRAFANA_PORT:-13000}:3000
    volumes:
      - ./data/grafana:/var/lib/grafana
